### ISSUE TITLE
Connect from Windows?

### ISSUE THREAD

**Issue by protik77** [chaos/mrsh#10]
Hi,

I need to connect to a server running mrsh from a Windows machine. Considering the client on the Windows side have to have the same munge key, is there any software that can do that?

**Comment by chu11** [comment]
I assume you're talking about a native windows client that is `mrsh` compatible.  This project doesn't implement one and I'd be shocked if someone else out there did.  I think your best bet is to run this `mrsh` project under cygwin, a VM, or something equivalent.

**Comment by protik77** [comment]
I see. Is the `mrsh` library available from cygwin or I have to compile it?

**Comment by chu11** [comment]
`mrsh` is a command line tool.  I imagine you'd have to compile this project.

**Comment by protik77** [comment]
I see. Thanks.
