### ISSUE TITLE
Authentication failure on localhost

### ISSUE THREAD

**Issue by Adam-osc** [chaos/mrsh#17]
I own two linux machines, on the first one munge and mrsh work without any issues. On the other I am able to connect to the first machine but not to localhost. On the first one connecting to localhost works. The versions of munge and mrsh are the same on both machines. I spent roughly a day trying to work this out by reading through straces of the servers and clients. I would be really happy if you had helped me resolve this issue.

**Comment by garlick** [comment]
I forget how "host equivalence" works but if it's based on reverse looking up the peer hostname, DNS and/or /etc/hosts might need to match what's in your rhosts or /etc/hosts.equiv file.

Post any errors or log messages that you have - that might jog a memory.

p.s. please consider switching to ssh.  Besides being more secure, it's actively supported and probably would be easier to debug in this situation.

**Comment by Adam-osc** [comment]
I decided to listen to your advice and rather than fixing this absurd issue migrated everything to ssh. Literally took me less time than what I spent debugging this problem.

The sole reason why I was using mrsh was because munge authentication was mentioned in my university's operating system lecture notes and it took my interest.

**Comment by garlick** [comment]
Good move.

[munge](https://github.com/dun/munge) is an excellent tool that we still use a lot when building distributed systems on HPC clusters.  It is actively maintained.

In contrast, mrsh was a hack that forked a copy of BSD `rsh` and mungified it.  It was still BSD `rsh` though, complete with bugs and unsafe internal practices.  It also doesn't secure network traffic in any way - it just uses munge for the initial authentication.  It's main advantage over ssh is being lightweight and fast, which is important when running many of them in parallel e.g. with [pdsh](https://github.com/chaos/pdsh).

In todays world ssh is fast enough and isn't a security incident waiting to happen.
