### ISSUE TITLE
union wait depreciated - suggested fix attached.

### ISSUE THREAD

**Issue by MakeItGreatAgain** [chaos/mrsh#9]
The following patch should make it work:

````
diff --git a/mrlogin/mrlogin.c b/mrlogin/mrlogin.c
index ccde09e..00d83d9 100644
--- a/mrlogin/mrlogin.c
+++ b/mrlogin/mrlogin.c
@@ -476,7 +476,7 @@ writeroob(int ignore)
 void
 catch_child(int ignore)
 {
-       union wait status;
+       int status;
        int pid;

        (void)ignore;
@@ -487,7 +487,7 @@ catch_child(int ignore)
                        return;
                /* if the child (reader) dies, just quit */
                if (pid < 0 || (pid == childpid && !WIFSTOPPED(status)))
-                       done((int)(status.w_termsig | status.w_retcode));
+                       done((int)(WTERMSIG(status) | WEXITSTATUS(status)));
        }
        /* NOTREACHED */
 }
`````

**Comment by garlick** [comment]
Usually we avoid touching this code unless there is a security issue or other critical problem.

Has a particular compiler/version or OS distro unable to compile this?

**Comment by MakeItGreatAgain** [comment]
No current Linux distribution seems to be able to compile the code. I'm using Fedora 30 and Debian 9.

Looking at a [related Debian bug report for tcsh](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837026), it is mentioned that "glibc-2.24 removed the deprecated BSD Union wait type".

**Comment by garlick** [comment]
Thanks.

**Comment by chu11** [comment]
It seems gnu removed the BSD backwards compatibility, so this seems ok.  @MakeItGreatAgain would you like to send a pull request?

**Comment by MakeItGreatAgain** [comment]
Would it be prudent to test for the BSD capability and only use the new method if it's not available? 

I wouldn't want to break anything older.

**Comment by chu11** [comment]
My understanding (via limited Googling) is that it was removed from BSD in the mid-1990s.  So while it would be prudent, I'm not sure it's worth the effort.  The fact it will not work on newer glibc is a bigger problem, so we should tackle that first.

If we want to be on the safe side, could run a configure check to see if `union wait` is defined.  If it is, use the old code, otherwise use the code provided above.

**Comment by MakeItGreatAgain** [comment]
I will look at this today.

**Comment by MakeItGreatAgain** [comment]
It looks as if the patch will work fine on current FreeBSD and OpenBSD.

I'd like to test that a bit later today and if there are no problems I will create a pull request - I don't feel a autoconf test is warranted as long as this works on modern BSD systems.

**Comment by garlick** [comment]
> I don't feel a autoconf test is warranted as long as this works on modern BSD systems.

Agreed.

**Comment by MakeItGreatAgain** [comment]
Will have time to test on BSD this weekend

**Comment by mdiep25** [comment]
this failed compile in sles15sp1
